export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/garden/index',
    'pages/encyclopedia/index',
    'pages/store/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/register/index',
    'pages/forgotPassword/index',
    'pages/emailVerify/index',
    'pages/diagnosis/index',
    'pages/diagnosisHistory/index',
    'pages/diagnosisDetail/index',
    'pages/recommendation/index',
    'pages/reminder/index',
    'pages/encyclopediaDetail/index',
    'pages/plantDetail/index',
    'pages/diary/index',
    'pages/writeDiary/index',
    'pages/diaryDetail/index',
    'pages/growthCurve/index',
    'pages/storeDetail/index',
    'pages/cart/index',
    'pages/orders/index',
    'pages/orderDetail/index',
    'pages/consultationList/index',
    'pages/consultation/index',
    'pages/knowledge/index',
    'pages/knowledgeDetail/index',
    'pages/address/index',
    'pages/addressEdit/index',
    'pages/notification/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#f46',
    navigationBarTitleText: '护花使者',
    navigationBarTextStyle: 'white',
    backgroundColor: '#fafafa',
  },
  requiredPrivateInfos: ['getLocation', 'chooseLocation'],
  permission: {
    'scope.userLocation': {
      desc: '用于获取您的位置信息，提供天气和养护建议',
    },
  },
  tabBar: {
    color: '#999999',
    selectedColor: '#f46',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/garden/index',
        text: '花园',
        iconPath: 'assets/tab-garden.png',
        selectedIconPath: 'assets/tab-garden-active.png',
      },
      {
        pagePath: 'pages/encyclopedia/index',
        text: '百科',
        iconPath: 'assets/tab-book.png',
        selectedIconPath: 'assets/tab-book-active.png',
      },
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tab-home.png',
        selectedIconPath: 'assets/tab-home-active.png',
      },
      {
        pagePath: 'pages/store/index',
        text: '商城',
        iconPath: 'assets/tab-store.png',
        selectedIconPath: 'assets/tab-store-active.png',
      },
      {
        pagePath: 'pages/profile/index',
        text: '我的',
        iconPath: 'assets/tab-profile.png',
        selectedIconPath: 'assets/tab-profile-active.png',
      },
    ],
  },
})
