// 自定义图标组件 - 使用 lucide-react-native
import React from 'react';
import { View, StyleSheet } from 'react-native';
import { LucideProps } from 'lucide-react-native';
import {
  Leaf,
  Flower2,
  Flower,
  Sprout,
  Trees,
  Sun,
  Cloud,
  CloudRain,
  Snowflake,
  Droplet,
  Droplets,
  Star,
  Search,
  Settings,
  User,
  Check,
  X,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Plus,
  Minus,
  Loader2,
  RefreshCw,
  Clock,
  Bell,
  BellOff,
  Calendar,
  Share2,
  Heart,
  MessageCircle,
  Scissors,
  Sparkles,
  Info,
  AlertTriangle,
  AlertCircle,
  Layers,
  Activity,
  TrendingUp,
  Home,
  Menu,
  MoreHorizontal,
  Palmtree,
  Moon,
  Umbrella,
  Stethoscope,
  Shield,
  ShieldCheck,
  Quote,
  Lightbulb,
  Edit2,
  Thermometer,
  Circle,
  Camera,
  Image,
  Book,
  BookOpen,
  Users,
  HelpCircle,
  StarHalf,
  ThermometerSun,
  CloudSnow,
  ClipboardList,
  Grid,
  List,
  Mail,
  Phone,
  MapPin,
  Globe,
  Wifi,
  Bluetooth,
  Volume2,
  VolumeX,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Trash2,
  Copy,
  Download,
  Upload,
  File,
  Folder,
  FolderOpen,
  Tag,
  Bookmark,
  Flag,
  Map,
  Navigation,
  Wind,
  type LucideIcon as LucideIconType,
} from 'lucide-react-native';

// 图标名称到 Lucide 组件的映射
const iconMap: Record<string, React.FC<LucideProps>> = {
  // 基础图标
  camera: Camera,
  'camera-plus': Camera,
  image: Image,
  'image-plus': Image,
  flower2: Flower2,
  flower: Flower,
  leaf: Leaf,
  'leaf-arrow': Leaf,
  book: Book,
  'book-open': BookOpen,
  user: User,
  users: Users,
  search: Search,
  settings: Settings,
  help: HelpCircle,
  star: Star,
  'star-half': StarHalf,
  'sun-medium': Sun,
  sun: Sun,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  snowflake: Snowflake,
  droplet: Droplet,
  droplets: Droplets,
  thermometer: Thermometer,
  'thermometer-sun': ThermometerSun,
  // 操作图标
  plus: Plus,
  minus: Minus,
  check: Check,
  'check-circle': Check,
  x: X,
  'x-circle': X,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  chevron: ChevronRight,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronLeft,
  loader: Loader2,
  'loader-2': Loader2,
  'refresh-ccw': RefreshCw,
  'refresh-cw': RefreshCw,
  clock: Clock,
  bell: Bell,
  'bell-off': BellOff,
  calendar: Calendar,
  share: Share2,
  'share-2': Share2,
  heart: Heart,
  message: MessageCircle,
  'message-circle': MessageCircle,
  scissors: Scissors,
  sparkles: Sparkles,
  info: Info,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  layers: Layers,
  activity: Activity,
  trending: TrendingUp,
  'trending-up': TrendingUp,
  home: Home,
  menu: Menu,
  more: MoreHorizontal,
  // 植物相关
  'plant-pot': Palmtree,
  sprout: Sprout,
  tree: Trees,
  plant: Palmtree,
  // 天气/环境
  'sun-horizon': Sun,
  moon: Moon,
  cloud: Cloud,
  umbrella: Umbrella,
  stethoscope: Stethoscope,
  shield: Shield,
  'shield-check': ShieldCheck,
  quote: Quote,
  lightbulb: Lightbulb,
  'edit-2': Edit2,
  circle: Circle,
  // 其他常用
  clipboard: ClipboardList,
  grid: Grid,
  list: List,
  mail: Mail,
  phone: Phone,
  'map-pin': MapPin,
  globe: Globe,
  wifi: Wifi,
  bluetooth: Bluetooth,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  'eye-off': EyeOff,
  trash: Trash2,
  copy: Copy,
  download: Download,
  upload: Upload,
  file: File,
  folder: Folder,
  'folder-open': FolderOpen,
  tag: Tag,
  bookmark: Bookmark,
  flag: Flag,
  map: Map,
  navigation: Navigation,
  wind: Wind,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
}

export function Icon({ name, size = 24, color = '#000' }: IconProps) {
  const IconComponent = iconMap[name];

  if (IconComponent) {
    return (
      <IconComponent
        size={size}
        color={color}
        strokeWidth={2}
      />
    );
  }

  // 默认返回空心圆
  return (
    <View
      style={[
        styles.fallback,
        {
          width: size,
          height: size,
          borderRadius: size / 2,
          borderWidth: 2,
          borderColor: color,
        },
      ]}
    />
  );
}

// 导出预定义图标组件列表，方便直接导入使用
export const Icons = {
  Camera: (props: Omit<LucideProps, 'name'>) => <Icon name="camera" {...props} />,
  Image: (props: Omit<LucideProps, 'name'>) => <Icon name="image" {...props} />,
  Flower2: (props: Omit<LucideProps, 'name'>) => <Icon name="flower2" {...props} />,
  Flower: (props: Omit<LucideProps, 'name'>) => <Icon name="flower" {...props} />,
  BookOpen: (props: Omit<LucideProps, 'name'>) => <Icon name="book-open" {...props} />,
  User: (props: Omit<LucideProps, 'name'>) => <Icon name="user" {...props} />,
  Search: (props: Omit<LucideProps, 'name'>) => <Icon name="search" {...props} />,
  Settings: (props: Omit<LucideProps, 'name'>) => <Icon name="settings" {...props} />,
  HelpCircle: (props: Omit<LucideProps, 'name'>) => <Icon name="help" {...props} />,
  Star: (props: Omit<LucideProps, 'name'>) => <Icon name="star" {...props} />,
  Clock: (props: Omit<LucideProps, 'name'>) => <Icon name="clock" {...props} />,
  Bell: (props: Omit<LucideProps, 'name'>) => <Icon name="bell" {...props} />,
  Droplets: (props: Omit<LucideProps, 'name'>) => <Icon name="droplets" {...props} />,
  Sun: (props: Omit<LucideProps, 'name'>) => <Icon name="sun" {...props} />,
  CloudRain: (props: Omit<LucideProps, 'name'>) => <Icon name="cloud-rain" {...props} />,
  Snowflake: (props: Omit<LucideProps, 'name'>) => <Icon name="snowflake" {...props} />,
  Plus: (props: Omit<LucideProps, 'name'>) => <Icon name="plus" {...props} />,
  X: (props: Omit<LucideProps, 'name'>) => <Icon name="x" {...props} />,
  Check: (props: Omit<LucideProps, 'name'>) => <Icon name="check" {...props} />,
  ArrowLeft: (props: Omit<LucideProps, 'name'>) => <Icon name="arrow-left" {...props} />,
  ArrowRight: (props: Omit<LucideProps, 'name'>) => <Icon name="arrow-right" {...props} />,
  ChevronRight: (props: Omit<LucideProps, 'name'>) => <Icon name="chevron-right" {...props} />,
  ChevronLeft: (props: Omit<LucideProps, 'name'>) => <Icon name="chevron-left" {...props} />,
  Loader2: (props: Omit<LucideProps, 'name'>) => <Icon name="loader" {...props} />,
  RefreshCw: (props: Omit<LucideProps, 'name'>) => <Icon name="refresh-cw" {...props} />,
  Calendar: (props: Omit<LucideProps, 'name'>) => <Icon name="calendar" {...props} />,
  Share2: (props: Omit<LucideProps, 'name'>) => <Icon name="share" {...props} />,
  Heart: (props: Omit<LucideProps, 'name'>) => <Icon name="heart" {...props} />,
  MessageCircle: (props: Omit<LucideProps, 'name'>) => <Icon name="message-circle" {...props} />,
  Scissors: (props: Omit<LucideProps, 'name'>) => <Icon name="scissors" {...props} />,
  Sparkles: (props: Omit<LucideProps, 'name'>) => <Icon name="sparkles" {...props} />,
  AlertTriangle: (props: Omit<LucideProps, 'name'>) => <Icon name="alert-triangle" {...props} />,
  AlertCircle: (props: Omit<LucideProps, 'name'>) => <Icon name="alert-circle" {...props} />,
  Layers: (props: Omit<LucideProps, 'name'>) => <Icon name="layers" {...props} />,
  Activity: (props: Omit<LucideProps, 'name'>) => <Icon name="activity" {...props} />,
  TrendingUp: (props: Omit<LucideProps, 'name'>) => <Icon name="trending-up" {...props} />,
  SunMedium: (props: Omit<LucideProps, 'name'>) => <Icon name="sun-medium" {...props} />,
  Info: (props: Omit<LucideProps, 'name'>) => <Icon name="info" {...props} />,
  Home: (props: Omit<LucideProps, 'name'>) => <Icon name="home" {...props} />,
  Stethoscope: (props: Omit<LucideProps, 'name'>) => <Icon name="stethoscope" {...props} />,
  History: (props: Omit<LucideProps, 'name'>) => <Icon name="history" {...props} />,
  ShoppingCart: (props: Omit<LucideProps, 'name'>) => <Icon name="shopping-cart" {...props} />,
  FileText: (props: Omit<LucideProps, 'name'>) => <Icon name="file-text" {...props} />,
  Shield: (props: Omit<LucideProps, 'name'>) => <Icon name="shield" {...props} />,
  ShieldCheck: (props: Omit<LucideProps, 'name'>) => <Icon name="shield-check" {...props} />,
  Lightbulb: (props: Omit<LucideProps, 'name'>) => <Icon name="lightbulb" {...props} />,
  Edit2: (props: Omit<LucideProps, 'name'>) => <Icon name="edit-2" {...props} />,
  Thermometer: (props: Omit<LucideProps, 'name'>) => <Icon name="thermometer" {...props} />,
  Circle: (props: Omit<LucideProps, 'name'>) => <Icon name="circle" {...props} />,
  Quote: (props: Omit<LucideProps, 'name'>) => <Icon name="quote" {...props} />,
  Cloud: (props: Omit<LucideProps, 'name'>) => <Icon name="cloud" {...props} />,
  Leaf: (props: Omit<LucideProps, 'name'>) => <Icon name="leaf" {...props} />,
  Sprout: (props: Omit<LucideProps, 'name'>) => <Icon name="sprout" {...props} />,
  Tree: (props: Omit<LucideProps, 'name'>) => <Icon name="trees" {...props} />,
  Umbrella: (props: Omit<LucideProps, 'name'>) => <Icon name="umbrella" {...props} />,
  Moon: (props: Omit<LucideProps, 'name'>) => <Icon name="moon" {...props} />,
  Plant: (props: Omit<LucideProps, 'name'>) => <Icon name="palmtree" {...props} />,
  Wind: (props: Omit<LucideProps, 'name'>) => <Icon name="wind" {...props} />,
  Mail: (props: Omit<LucideProps, 'name'>) => <Icon name="mail" {...props} />,
  Lock: (props: Omit<LucideProps, 'name'>) => <Icon name="lock" {...props} />,
  Unlock: (props: Omit<LucideProps, 'name'>) => <Icon name="unlock" {...props} />,
  Eye: (props: Omit<LucideProps, 'name'>) => <Icon name="eye" {...props} />,
  EyeOff: (props: Omit<LucideProps, 'name'>) => <Icon name="eye-off" {...props} />,
  Trash2: (props: Omit<LucideProps, 'name'>) => <Icon name="trash" {...props} />,
  ShieldCheck: (props: Omit<LucideProps, 'name'>) => <Icon name="shield-check" {...props} />,
  ArrowLeftRight: (props: Omit<LucideProps, 'name'>) => <Icon name="arrow-right" {...props} />,
};

const styles = StyleSheet.create({
  fallback: {
    backgroundColor: 'transparent',
  },
});

export default Icon;
