from sqlalchemy.orm import Session
from app.models.plant import Plant

# 47种植物基础数据
PLANT_DATA = [
    {"yolo_class_id": 0, "name": "非洲紫罗兰", "scientific_name": "Saintpaulia ionantha", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，避免叶片浇水", "temperature_range": "18-24°C", "humidity_range": "40-60%", "is_toxic": False, "features": ["开花", "耐阴"], "survival_rate": 85, "description": "非洲紫罗兰株型小巧，花色丰富，是非常受欢迎的室内开花植物。"},
    {"yolo_class_id": 1, "name": "芦荟", "scientific_name": "Aloe vera", "category": "多肉", "care_level": 1, "beginner_friendly": 5, "light_requirement": "full", "water_requirement": "biweekly", "watering_tip": "干透再浇，避免积水", "temperature_range": "13-27°C", "humidity_range": "30-50%", "is_toxic": True, "features": ["药用", "净化空气"], "survival_rate": 95, "description": "芦荟是多肉植物，叶片肥厚储水能力强，非常耐旱，适合新手。"},
    {"yolo_class_id": 2, "name": "红掌", "scientific_name": "Anthurium andraeanum", "category": "室内", "care_level": 2, "beginner_friendly": 3, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润但不要积水", "temperature_range": "18-30°C", "humidity_range": "60-80%", "is_toxic": True, "features": ["开花", "净化空气"], "survival_rate": 80, "description": "红掌花姿奇特，佛焰苞红色鲜艳，是高档室内观花植物。"},
    {"yolo_class_id": 3, "name": "散尾葵", "scientific_name": "Dypsis lutescens", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "20-30°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["净化空气", "加湿"], "survival_rate": 85, "description": "散尾葵是常见的大型室内观叶植物，姿态优美。"},
    {"yolo_class_id": 4, "name": "文竹", "scientific_name": "Asparagus setaceus", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，避免干旱", "temperature_range": "15-25°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["净化空气", "观赏"], "survival_rate": 80, "description": "文竹枝叶纤细秀丽，姿态优雅，是著名的室内观叶植物。"},
    {"yolo_class_id": 5, "name": "秋海棠", "scientific_name": "Begonia", "category": "开花", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润但不要积水", "temperature_range": "18-25°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["开花", "观赏"], "survival_rate": 80, "description": "秋海棠花色丰富，叶形优美，是常见的室内观赏花卉。"},
    {"yolo_class_id": 6, "name": "天堂鸟", "scientific_name": "Strelitzia reginae", "category": "室内", "care_level": 3, "beginner_friendly": 3, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "生长期保持土壤湿润", "temperature_range": "20-30°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["开花", "大型"], "survival_rate": 75, "description": "天堂鸟叶片硕大，花姿奇特，是高端室内观叶植物。"},
    {"yolo_class_id": 7, "name": "鸟巢蕨", "scientific_name": "Asplenium nidus", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["净化空气", "耐阴"], "survival_rate": 85, "description": "鸟巢蕨叶片呈放射状生长，形似鸟巢，非常美观。"},
    {"yolo_class_id": 8, "name": "波士顿蕨", "scientific_name": "Nephrolepis exaltata", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "frequent", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "18-24°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["净化空气", "垂吊"], "survival_rate": 80, "description": "波士顿蕨枝叶下垂，姿态优美，是很好的垂吊观叶植物。"},
    {"yolo_class_id": 9, "name": "竹芋", "scientific_name": "Maranta leuconeura", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，避免干旱", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["净化空气", "耐阴"], "survival_rate": 85, "description": "竹芋叶片有美丽斑纹，是著名的室内观叶植物。"},
    {"yolo_class_id": 10, "name": "一叶兰", "scientific_name": "Aspidistra elatior", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "low", "water_requirement": "biweekly", "watering_tip": "干透再浇，耐干旱", "temperature_range": "10-25°C", "humidity_range": "40-60%", "is_toxic": False, "features": ["耐阴", "易养护"], "survival_rate": 95, "description": "一叶兰极耐阴，是最易养护的室内观叶植物之一。"},
    {"yolo_class_id": 11, "name": "金钱草", "scientific_name": "Lysimachia christinae", "category": "草本", "care_level": 1, "beginner_friendly": 5, "light_requirement": "partial", "water_requirement": "frequent", "watering_tip": "保持土壤湿润，喜水", "temperature_range": "15-25°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["净化空气", "水培"], "survival_rate": 90, "description": "金钱草叶片圆形似钱币，寓意好，易于养护。"},
    {"yolo_class_id": 12, "name": "万年青", "scientific_name": "Dieffenbachia seguine", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "18-28°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["净化空气", "观赏"], "survival_rate": 85, "description": "万年青叶片宽大翠绿，是常见的室内观叶植物。"},
    {"yolo_class_id": 13, "name": "蟹爪兰", "scientific_name": "Schlumbergera truncata", "category": "开花", "care_level": 3, "beginner_friendly": 3, "light_requirement": "partial", "water_requirement": "biweekly", "watering_tip": "花期控制浇水，避免积水", "temperature_range": "15-25°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["开花", "冬季"], "survival_rate": 75, "description": "蟹爪兰花期在冬季，枝条下垂，花朵鲜艳。"},
    {"yolo_class_id": 14, "name": "菊花", "scientific_name": "Chrysanthemum morifolium", "category": "开花", "care_level": 2, "beginner_friendly": 4, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "保持土壤湿润但不积水", "temperature_range": "15-25°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["开花", "药用"], "survival_rate": 80, "description": "菊花是中国传统名花，花色丰富，花期长。"},
    {"yolo_class_id": 15, "name": "浪星竹芋", "scientific_name": "Calathea orbifolia", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["观赏", "耐阴"], "survival_rate": 80, "description": "浪星竹芋叶片大而有美丽斑纹，非常美观。"},
    {"yolo_class_id": 16, "name": "水仙", "scientific_name": "Narcissus tazetta", "category": "开花", "care_level": 2, "beginner_friendly": 3, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "保持水分充足", "temperature_range": "10-18°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["开花", "冬季"], "survival_rate": 75, "description": "水仙是中国传统名花，花香浓郁，花期在春节。"},
    {"yolo_class_id": 17, "name": "龙血树", "scientific_name": "Dracaena fragrans", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "biweekly", "watering_tip": "干透再浇，避免积水", "temperature_range": "18-28°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["净化空气", "大型"], "survival_rate": 85, "description": "龙血树株型优美，是常见的大型室内观叶植物。"},
    {"yolo_class_id": 18, "name": "黛粉叶", "scientific_name": "Dieffenbachia amoena", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "18-28°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["净化空气", "观赏"], "survival_rate": 80, "description": "黛粉叶叶片有美丽斑纹，是常见的室内观叶植物。"},
    {"yolo_class_id": 19, "name": "海芋", "scientific_name": "Alocasia macrorrhiza", "category": "室内", "care_level": 3, "beginner_friendly": 2, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，生长期多浇水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": True, "features": ["大型", "观赏"], "survival_rate": 70, "description": "海芋叶片硕大，姿态优美，是高端室内观叶植物。"},
    {"yolo_class_id": 20, "name": "常春藤", "scientific_name": "Hedera helix", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "10-20°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["净化空气", "垂吊"], "survival_rate": 90, "description": "常春藤是常见的垂吊观叶植物，净化空气能力强。"},
    {"yolo_class_id": 21, "name": "风信子", "scientific_name": "Hyacinthus orientalis", "category": "开花", "care_level": 2, "beginner_friendly": 3, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "保持水分充足", "temperature_range": "10-18°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["开花", "花香"], "survival_rate": 75, "description": "风信子花色丰富，花香浓郁，是常见的球根花卉。"},
    {"yolo_class_id": 22, "name": "铁十字秋海棠", "scientific_name": "Begonia masoniana", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，避免叶面浇水", "temperature_range": "18-25°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["观赏", "耐阴"], "survival_rate": 80, "description": "铁十字秋海棠叶片有独特斑纹，非常美观。"},
    {"yolo_class_id": 23, "name": "玉树", "scientific_name": "Crassula ovata", "category": "多肉", "care_level": 1, "beginner_friendly": 5, "light_requirement": "full", "water_requirement": "monthly", "watering_tip": "非常耐旱，干透再浇", "temperature_range": "15-25°C", "humidity_range": "30-50%", "is_toxic": True, "features": ["多肉", "观赏"], "survival_rate": 95, "description": "玉树叶片肥厚，株型优美，是常见的多肉植物。"},
    {"yolo_class_id": 24, "name": "长寿花", "scientific_name": "Kalanchoe blossfeldiana", "category": "开花", "care_level": 1, "beginner_friendly": 4, "light_requirement": "full", "water_requirement": "biweekly", "watering_tip": "耐旱，干透再浇", "temperature_range": "15-25°C", "humidity_range": "40-60%", "is_toxic": False, "features": ["开花", "花期长"], "survival_rate": 90, "description": "长寿花花期长花色丰富，是受欢迎的室内开花植物。"},
    {"yolo_class_id": 25, "name": "萱草", "scientific_name": "Hemerocallis", "category": "开花", "care_level": 2, "beginner_friendly": 4, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "15-30°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["开花", "观赏"], "survival_rate": 85, "description": "萱草花色鲜艳，是常见的园林观赏花卉。"},
    {"yolo_class_id": 26, "name": "铃兰", "scientific_name": "Convallaria majalis", "category": "开花", "care_level": 3, "beginner_friendly": 3, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "10-20°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["开花", "花香"], "survival_rate": 70, "description": "铃兰花小而香，是著名的香花植物。"},
    {"yolo_class_id": 27, "name": "发财树", "scientific_name": "Pachira glabra", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "biweekly", "watering_tip": "干透再浇，避免积水", "temperature_range": "18-28°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["净化空气", "招财"], "survival_rate": 85, "description": "发财树寓意好，是最受欢迎的室内观叶植物之一。"},
    {"yolo_class_id": 28, "name": "龟背竹", "scientific_name": "Monstera deliciosa", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": True, "features": ["净化空气", "大型"], "survival_rate": 85, "description": "龟背竹叶片奇特，是最受欢迎的室内观叶植物之一。"},
    {"yolo_class_id": 29, "name": "兰花", "scientific_name": "Cymbidium", "category": "开花", "care_level": 3, "beginner_friendly": 3, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持植材湿润但不过湿", "temperature_range": "15-28°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["开花", "花香"], "survival_rate": 75, "description": "兰花是中国传统名花，品种繁多，花香幽雅。"},
    {"yolo_class_id": 30, "name": "棕竹", "scientific_name": "Rhapis excelsa", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "15-28°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["净化空气", "耐阴"], "survival_rate": 85, "description": "棕竹株型优美，是常见的大型室内观叶植物。"},
    {"yolo_class_id": 31, "name": "白掌", "scientific_name": "Spathiphyllum wallisii", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，喜水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": True, "features": ["开花", "净化空气"], "survival_rate": 90, "description": "白掌花洁白素雅，是常见的室内开花观叶植物。"},
    {"yolo_class_id": 32, "name": "一品红", "scientific_name": "Euphorbia pulcherrima", "category": "开花", "care_level": 2, "beginner_friendly": 3, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "15-25°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["开花", "节日"], "survival_rate": 75, "description": "一品红是著名的圣诞花卉，苞片红色鲜艳。"},
    {"yolo_class_id": 33, "name": "红斑竹叶", "scientific_name": "Calathea roseopicta", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["观赏", "耐阴"], "survival_rate": 80, "description": "红斑竹叶叶片有美丽斑纹，非常美观。"},
    {"yolo_class_id": 34, "name": "酒瓶兰", "scientific_name": "Beaucarnea recurvata", "category": "多肉", "care_level": 1, "beginner_friendly": 5, "light_requirement": "full", "water_requirement": "monthly", "watering_tip": "极耐旱，干透再浇", "temperature_range": "15-28°C", "humidity_range": "30-50%", "is_toxic": False, "features": ["多肉", "观赏"], "survival_rate": 95, "description": "酒瓶兰茎部膨大，形态独特，是常见的多肉植物。"},
    {"yolo_class_id": 35, "name": "绿萝", "scientific_name": "Epipremnum aureum", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "15-30°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["净化空气", "耐阴", "易养护"], "survival_rate": 98, "description": "绿萝是最受欢迎的室内绿植，净化空气能力强，易于养护。"},
    {"yolo_class_id": 36, "name": "竹节秋海棠", "scientific_name": "Begonia maculata", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "18-25°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["开花", "观赏"], "survival_rate": 80, "description": "竹节秋海棠枝条有节，叶片有斑点，非常美观。"},
    {"yolo_class_id": 37, "name": "响尾蛇竹芋", "scientific_name": "Calathea lancifolia", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "low", "water_requirement": "weekly", "watering_tip": "保持土壤湿润，经常喷水", "temperature_range": "18-28°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["观赏", "耐阴"], "survival_rate": 80, "description": "响尾蛇竹芋叶片有独特斑纹，非常美观。"},
    {"yolo_class_id": 38, "name": "橡皮树", "scientific_name": "Ficus elastica", "category": "室内", "care_level": 1, "beginner_friendly": 4, "light_requirement": "full", "water_requirement": "biweekly", "watering_tip": "干透再浇", "temperature_range": "15-28°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["净化空气", "大型"], "survival_rate": 90, "description": "橡皮树叶片厚实有光泽，是常见的室内观叶植物。"},
    {"yolo_class_id": 39, "name": "苏铁", "scientific_name": "Cycas revoluta", "category": "室内", "care_level": 2, "beginner_friendly": 4, "light_requirement": "full", "water_requirement": "monthly", "watering_tip": "耐旱，干透再浇", "temperature_range": "15-28°C", "humidity_range": "40-60%", "is_toxic": True, "features": ["大型", "观赏"], "survival_rate": 85, "description": "苏铁形态古朴，是著名的观赏植物。"},
    {"yolo_class_id": 40, "name": "鹅掌柴", "scientific_name": "Schefflera octophylla", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "15-25°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["净化空气", "易养护"], "survival_rate": 92, "description": "鹅掌柴叶片掌状，是最易养护的室内观叶植物之一。"},
    {"yolo_class_id": 41, "name": "虎皮兰", "scientific_name": "Sansevieria trifasciata", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "partial", "water_requirement": "monthly", "watering_tip": "极耐旱，2-4周浇一次", "temperature_range": "15-30°C", "humidity_range": "30-50%", "is_toxic": False, "features": ["净化空气", "耐旱"], "survival_rate": 98, "description": "虎皮兰叶片挺拔，是最适合新手的室内植物之一。"},
    {"yolo_class_id": 42, "name": "紫露草", "scientific_name": "Tradescantia pallida", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "partial", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "15-25°C", "humidity_range": "50-70%", "is_toxic": False, "features": ["垂吊", "观赏"], "survival_rate": 90, "description": "紫露草叶片紫色，枝条下垂，非常美观。"},
    {"yolo_class_id": 43, "name": "郁金香", "scientific_name": "Tulipa gesneriana", "category": "开花", "care_level": 2, "beginner_friendly": 3, "light_requirement": "full", "water_requirement": "weekly", "watering_tip": "保持土壤湿润", "temperature_range": "10-20°C", "humidity_range": "50-70%", "is_toxic": True, "features": ["开花", "观赏"], "survival_rate": 75, "description": "郁金香是世界著名花卉，花色丰富，花姿优美。"},
    {"yolo_class_id": 44, "name": "捕蝇草", "scientific_name": "Dionaea muscipula", "category": "草本", "care_level": 3, "beginner_friendly": 2, "light_requirement": "full", "water_requirement": "frequent", "watering_tip": "保持基质湿润，喜软水", "temperature_range": "15-30°C", "humidity_range": "60-80%", "is_toxic": False, "features": ["食虫", "趣味"], "survival_rate": 65, "description": "捕蝇草叶片能捕食昆虫，是有趣的食虫植物。"},
    {"yolo_class_id": 45, "name": "丝兰", "scientific_name": "Yucca filamentosa", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "full", "water_requirement": "monthly", "watering_tip": "耐旱，干透再浇", "temperature_range": "15-30°C", "humidity_range": "30-50%", "is_toxic": True, "features": ["观赏", "耐旱"], "survival_rate": 90, "description": "丝兰叶片细长如丝，是独特的观赏植物。"},
    {"yolo_class_id": 46, "name": "金钱树", "scientific_name": "Zamioculcas zamiifolia", "category": "室内", "care_level": 1, "beginner_friendly": 5, "light_requirement": "low", "water_requirement": "biweekly", "watering_tip": "干透再浇，非常耐旱", "temperature_range": "15-28°C", "humidity_range": "40-60%", "is_toxic": True, "features": ["净化空气", "招财"], "survival_rate": 95, "description": "金钱树枝叶繁茂，寓意好，是受欢迎的室内植物。"}
]


def seed_plants(db: Session):
    """初始化植物数据"""
    count = 0
    for plant_data in PLANT_DATA:
        # 检查是否已存在
        existing = db.query(Plant).filter(Plant.yolo_class_id == plant_data["yolo_class_id"]).first()
        if not existing:
            db.add(Plant(**plant_data))
            count += 1
    db.commit()
    print(f"已初始化 {count} 种植物数据 (共 {len(PLANT_DATA)} 种)")


if __name__ == "__main__":
    from app.core.database import SessionLocal
    db = SessionLocal()
    try:
        seed_plants(db)
    finally:
        db.close()
